export const ROUTES = {
  HOME:          '/',
  ABOUT:         '/about',
  SERVICES:      '/services',
  PORTFOLIO:     '/portfolio',
  TEAM:          '/team',
  CONTACT:       '/contact',
  FAQ:           '/faq',
  PARTNERS:      '/partners',
  IMPACT:        '/impact',
  PRESS:         '/press',
  TESTIMONIALS:  '/testimonials',
  NEWSLETTER:    '/newsletter',
  SEARCH:        '/search',
  BLOG:          '/blog',
  EVENTS:        '/events',
  ALUMNI:        '/alumni',
  ALUMNI_SUBMIT: '/alumni/submit',
  CAREERS:       '/careers',
  VOLUNTEER:     '/volunteer',
  APPLY:         '/apply',
  APPLY_SUCCESS: '/apply/success',
  PORTAL:        '/portal',
  INTERNAL:      '/internal',
  ADMIN:         '/admin',
  LOGIN:         '/login',
  REGISTER:      '/register',
  PRIVACY:       '/legal/privacy',
  TERMS:         '/legal/terms',
  COOKIES:       '/legal/cookies',
  ACCESSIBILITY: '/legal/accessibility',
} as const

export type Route = typeof ROUTES[keyof typeof ROUTES]
